### ISSUE TITLE
package and class name

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#1]
what's the best name for this package and the main class?

NDSplines
NdSplines
SplineND
ndsplines
NDBSplines
ndbsplines
interpnd

etc.

**Comment by ixjlyons** [comment]
For the main class, in the SciPy codebase I see both:

- `Nd`: `NdPPoly`
- `ND`: `NDInterpolatorBase`, `LinearNDInterpolator`, `NearestNDInterpolator`

I personally find `NDSpline` or `NDBSpline` the most appealing, but I don't really have strong rationale. For the sake of specificity, maybe `NDBSpline` makes the most sense.

I'd say that unless more features will be added, going with the all lowercase name of the main class as the package name makes sense. I like `interpnd`, but that might be a bit too general.

**Comment by sixpearls** [comment]
What do you think of `[B]SplineNDInterpolator` ? I can't tell how much that family of names is supposed to be user facing. I think `NdPPoly` is designed to be outward  which would be `NdBSpline`.

I think `BSplineNDInterpolator` might be my favorite for the class: it is specific, follows CamelCase, and doesn't clump all the capital letters in an aesthetically unappealing way.

`ndbspline` probably makes a better package name, though. 

Using B-Splines, we actually can capture both "linear" and "nearest-neighbor" interpolation, which are the two main methods of `scipy.interpolate.interpn`, so it would also make sense to use a more general name for the class or package.

**Comment by ixjlyons** [comment]
`BSplineNDInterpolator` sounds good to me :+1:

After some thought and a bit of reading, I'm actually back to `ndspline` (or `ndsplines` for minimal effort). `ndbspline` isn't quite as nice to read and type, and the fact that the package implements spline interpolation via B-splines doesn't necessarily have to be highlighted in the name.

`interpnd` is still good with me. The only kind of interpolation I've come across that isn't polynomial or spline-based (or a degenerate case like linear or nearest neighbor) is sinc interpolation, but that's kind of its own thing and probably not the first thing that comes to mind.

**Comment by sixpearls** [comment]
Closed by 9f4bc033d045ae4bc9693cf607a559fd2cfa720e .

**Comment by sixpearls** [comment]
And obviously #8

**Comment by sixpearls** [comment]
I am playing with a derivative/antiderivative feature, and I realized the class name "Interpolator" is actually incorrect.  I may want to change the class name to `NDSpline` as the previous favorite.

**Comment by sixpearls** [comment]
`NDSpline` class and `ndspline` package name.
