### ISSUE TITLE
updating boundary condition API

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#24]
As mentioned in #23, I do have one possible API change to the `make_interp_spline` function. SciPy's API for the boundary conditions is, in my opinion, slightly inconsistent. The two boundaries can be different if they are both defined using a particular derivative = 0 condition (pinned vs clamped for beam boundary conditions), but the "not-a-knot" condition can only be applied to both sides or neither. I believe this is purely an API choice, and it would be relatively straightforward to add the functionality.

Cons:
API design review
possibly more challenging test development

Pros: 
Symetric (aesthetically pleasing) API
slightly more flexible usage (limited practical value)

Do you think this is worth developing? My biggest concern is the test development effort, so if it wouldn't change substantially I would lean towards doing it.

**Comment by sixpearls** [comment]
@ixjlyons What do you think of this feature?

The [SciPy API](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.make_interp_spline.html#scipy.interpolate.make_interp_spline) has three types of input:
   1. `None`,  `(None, None)`, or `'not-a-knot'` (default): apply not-a-knot boundary condition to both ends 
   2. `2-tuple` to specify the boundary condition on either end. The elements must be either
       1. `2-tuple` defined by `(derivative_specified, specified_value)`: where the `derivative_specified`-order derivative is fixed to the `specified_value`
       2. strings from "natural" or "clamped": apply `(2,0.0)` or `(1,0.0)` of the previous specification method, respectively

Upon further investigation, this might take a bit of work. I believe the current logic for creating the knots applies either the not-a-knot algorithm to both sides or the derivative-spec algorithm to both sides. It would need to be re-factored so the knot generation portion could apply either algorithm to each side independently. Other portions of SciPy code may be impacted as well, notably the coefficient padding that happens. It is also possible there is something about algorithm that make it impossible to apply not-a-knot to only one side.

**Comment by ixjlyons** [comment]
To make sure I understand correctly: you're proposing making it a single API for specifying the boundary conditions (maybe keep the `None` special case?) and this would involve making it possible to use the not-a-knot bc one side only? Seems to me to be nice to have but not essential.

**Comment by sixpearls** [comment]
Yes, that is what I was thinking for this proposed feature. I currently have module variables to flag SciPy's string values. The argument for the `bcs` must be broadcastable to `(xdim, 2)`, so that each dimension of the input can be specified on either end -- currently only not-a-knot, clamped, or pinned.

I think the best API would be based on passing in `deriv_specified` and `specified_value`. We can use a `deriv_specified=-1` or `deriv_specified=0` and/or `specified_value=nan` to indicate not-a-knot. I have two ideas that use this concept:

1. We can break them up into two different input arguments (int and float array respectively), each broadcastable to `(xdim, 2)`. 

2. We can require a single (float) array of shape `(xdim, 2, 2)`, where the first axis specifies the input dimension, the second axis specifies the end, and the last axis specifies `deriv_specified`/`specified_value`. 

I suppose the main benefit of the first option is the aesthetics of specifying holding the specs in arrays of the correct type. The second option allows the flags to hold the spec directly which would actually make it easier for the user. For example, to apply the pinned condition to both sides of all input dimensions, it would be convenient to pass `bcs=ndsplines.pinned` where `ndsplines.pinned = np.array([2,0])`, and have it be broadcast appropriately.

I will go ahead and prototype the second version.

**Comment by sixpearls** [comment]
Closed by #27
