### ISSUE TITLE
Add pickling functionality

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#32]
@ixjlyons Do you think it would be a nice feature to add some pickling functionality? I'm not sure how useful it would be practically, since the least squares and interpolating constructors are relatively fast, deterministic, etc. But it may help the aesthetic "completeness" or self-containment. I might also use it in other projects as a discipline, but it would be easy to add it to the other project if needed. For that project, I could also just store the arguments to the least square/interpolating constructors.

**Comment by ixjlyons** [comment]
Seems like it'd be nice to have to me. Does pickling the `BSplineNDInterpolator` object not just work currently?

**Comment by sixpearls** [comment]
I never checked, actually. All of the data that is actually kept is in NumPy arrays of standard types. The only possible question is the `impl` attribute, which we shouldn't want to save to disk, anyway. I am not actually very familiar with Pickle and was using it as a general short hand for de/serializing objects.

**Comment by ixjlyons** [comment]
Yeah it does seem to work currently, though I agree it storing the `impl` attribute isn't ideal.

Serializing just the arrays/args needed to re-construct the "fitted" spline would be good and avoids some of the usual concerns with pickling. Then you could have `to_pickle`/`from_pickle` or `to_file`/`from_file` methods.

**Comment by ixjlyons** [comment]
Another idea would be going back to `impl` as a module-wide variable and call it a day

**Comment by sixpearls** [comment]
Let's write an instance method `to_file` and module function `from_file` that writes/reads the `__init__` arguments in a single `.npz` file.

I don't remember what the motivation was for `impl` as a class attribute rather than module or instance. It does seem nice as a module attribute so pickle "just works" the right way (not that we're using it). A per-instance attribute could also allow using the better implementation for specific tasks in the same work space, although it is unlikely anyone would practically find a benefit to doing so.

**Comment by sixpearls** [comment]
Closed by #34
