### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#5]
Where possible, we should capture mathematical properties as much as possible. I am collecting a bunch of test ideas below. I have some general API tests, but you may be better at covering that.

Earlier I asked, 
> is profiling part of testing? maybe we could check that the computation scales with dimension, number of points, etc in some way?

I think the answer is no.

API to test
-----------
- [x] "squeeze" logic (#13)
- [x] tidy from pandas dataframe
- [x] tidy from numpy array
- [x] to/from file
- [x] derivative/antiderivative API preserves attributes other than knots and coefficients, including: order, periodicity, yshape, etc.

Math to test
--------------
- [ ] `NDSpline`
    - [ ] compare evaluation of random 1-D splines (generate knots, coefficients), to either the wrapped FITPACK `splev` or to `BSpline` for k=0,1,2,3. Also compare with derivatives (nu > 0). Also test external evaluations (extrapolation) -- may need lower tolerance?
    - [ ] compare evaluation of random 2-D splines to wrapped FITPACK 2-D spline, `bisplev` may be the only way to pass in the knots and coefficients directly. Both functional and class-based wrappers support derivatives on evaluate.
    - [ ] periodicity API -- I actually haven't played with this too much. 
    - for both 1-D and 2-D, make sure to try different knot multiplcities
    - SciPy also compares to a couple testing-only implementations
    - Calculus:
        - [ ] call of derivative should give same as original call with nu > 1, verify with multiple dimensions (at least 2), all partial derivatives, possibly higher order
        - [ ] derivative of antiderivative should give original (check coefficients, knots, orders)
        - [ ] compare calling antiderivative with nu > 1 vs original with appropriate nu
        - [ ] antiderivative of derivative should give original + (potential) offset -- I think the best thing to do would be to interpolate to construct original, then interpolate a constant over the same x values, then add coefficients
        - [ ] make sure shape is still consistent
        - [ ] verify order of partial derivatives order doesn't matter (for xdim > 1)

- [x] `make_interp_spline`, for 1-D and 2-D?
    - [ ] interpolant(data_x) = data_y
    - [ ] all combinations of boundary conditions -- evaluate derivatives for derivative specified BC's, confirm not-a-knot behavior is as expected (panels near edge have same derivatives, I believe (k+1)/2 panels)
    - [ ] not sure if it's better to use a few specified functions to evaluate or just random data
    - [x] k's = 0,1,2,3, (all combinations for 2-D?)
    - [x] 1-D: compare coefficients & knots to SciPy's `make_interp_spline` and/or FITPACK `splprep`
    - [x] 2-D: compare coefficients & knots to `RectBivariateSpline`
    - I am not sure how else to test knot construction or coefficient solving
- [ ] `make_lsq_spline`
     - [ ] compare 1-D fit to `make_lsq_spline`
     - [ ] compare 2-D fit to `LSQBivariateSpline`
     - [ ] k's = 0,1,2,3, (all combinations for 2-D?)
     - [ ] could use specific functions with noise and evaluate residual, etc.? If we generate the samples from a spline with noise, should be possible to compare LSQ and generator spline coefficients.

**Comment by ixjlyons** [comment]
> should we make sure the residual is proportional to the noise standard deviation?

That's a neat idea. Testing various combinations of boundary conditions sounds like a good idea to me too.

Another aspect to test would be just exercising the API, getting expected exceptions with bad inputs, etc.

Profiling scripts could go in a `benchmarks/` folder maybe and run for one specific environment in CI or just run manually before releases or something. There could even be a short docs page with some profiling notes and info from running the scripts.

**Comment by sixpearls** [comment]
Would the sphinx-gallery thing be a way to include benchmarks in the docs+CI?

Everything else sounds good.

**Comment by ixjlyons** [comment]
Yeah it could. I'm not sure how flexible it is with where the scripts can be placed (i.e. in two different directories) and where they appear in the docs though.

**Comment by sixpearls** [comment]
In terms of testing the API, we should also make sure shapes of inputs are handled correctly (broadcasting if possible, error handling if not) and produce outputs with the right shapes. E.g., see #13 

This is just an explicit example of your previous comment that I did not want to lose.

**Comment by sixpearls** [comment]
@ixjlyons not sure if you have been getting the updates, but I reviewed some of the relevant SciPy tests and came up with a fairly thorough set of (mathematical) tests.

**Comment by sixpearls** [comment]
- Eval comparison:
    - [x] compare evaluation of random 1-D splines (generate knots, coefficients), to either the wrapped FITPACK `splev` or to `BSpline` for k=0,1,2,3. Also compare with derivatives (nu > 0). Also test external evaluations (extrapolation) -- may need lower tolerance?
        - [x] compare eval with extrap = true, periodic = false
        - [x] compare eval with periodic = True
        - [x] compare eval with derivative for eahc k
    - [x] compare evaluation of random 2-D splines to wrapped FITPACK 2-D spline, `bisplev` may be the only way to pass in the knots and coefficients directly. Both functional and class-based wrappers support derivatives on evaluate.
        - [x] compare eval with extrap = true, periodic = false
        - [x] double check periodic=True is actually periodic ?
        - [x] compare eval with derivative for eahc k
- Calculus:
    - [x] call of derivative should give same as original call with nu > 1, verify with multiple dimensions (at least 2), all partial derivatives, possibly higher order
    - [x] derivative of antiderivative should give original (check coefficients, knots, orders)
    - [x] compare calling antiderivative with nu > 1 vs original with appropriate nu
    - [x] antiderivative of derivative should give original + (potential) offset -- I think the best thing to do would be to interpolate to construct original, then interpolate a constant over the same x values, then add coefficients
    - [x] verify order of partial derivatives order doesn't matter (for xdim > 1)
    - [x] verify derivaitve(-nu) = antiderivative(nu) and reverse
    - [x] verify ValueError on derivative(nu) for nu > k

- [x] `make_interp_spline`
    - [x] interpolant(data_x) = data_y, for random splines?
    - [x] 1-D: compare coefficients & knots to SciPy's `make_interp_spline` and/or FITPACK `splprep`
    - [x] 2-D: compare coefficients & knots to `RectBivariateSpline`
    - [x] repeat everything with tidy?
        - [x] pandas
        - [x] numpy array

- [x] `make_lsq_spline`
    - [x] check that fitting noisy data from a spline with the same knots should show accuracy improve with signal-to-noise ratio
    - [x] compare 1-D fit to `make_lsq_spline` (same data --> same coeffs)
    - [x] compare 2-D fit to `LSQBivariateSpline` (same data --> same coeffs) -- skipped because `LSQBivariateSpline` seems inconsistent
    - Note, due to some issues with both `scipy.interpolate.make_lsq_spline` and `LSQBivariateSpline`, these comparisons are not reliably run. 

      For the 1-d case, there seemed to be a numerical error depending on the particular random spline, which may be related to https://github.com/xianyi/OpenBLAS/issues/2137. Due to this issue, the creation and comparison is wrapped in a try-except flow.

      For the 2-d case, certain random splines (but not all) would cause a segfault on all platforms. I speculate that scipy is not defensively guarding the inputs to the fitpack's FORTRAN code, but I am not sure. 

     Since we do test the behavior of ndsplines quite well, I feel comfortable not having confident agreement with other implementations.

As of a544987be3189bb8d1aeb83ddd27c09833de0e21, the code coverage seems fairly complete. I will close this.
