### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ddevetak** [kb-press/ndsplines#54]
Hello, 

the installation of the package doesn't work "pip install ndsplines". Using Mac OS 0.14.5

ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_j/j55kt1rj2bd7zqnlc2269m940000gn/T/pip-install-dQhLq8/ndsplines/setup.py'"'"'; __file__='"'"'/private/var/folders/_j/j55kt1rj2bd7zqnlc2269m940000gn/T/pip-install-dQhLq8/ndsplines/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/_j/j55kt1rj2bd7zqnlc2269m940000gn/T/pip-install-dQhLq8/ndsplines/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_j/j55kt1rj2bd7zqnlc2269m940000gn/T/pip-install-dQhLq8/ndsplines/setup.py", line 26, in <module>
        depends=[os.path.join(name, "{}.h".format(extname))]),
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: 'ndsplines/_bspl.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ixjlyons** [comment]
Note that we don't officially support Python 2, however I think this can be fixed by adding the pyx file to MANIFEST.in. I'm not quite sure why it's necessary, but I can investigate further and we might as well include it if it solves an installation problem (there may be additional problems uncovered after getting beyond this point in the installation process though).

**Comment by ixjlyons** [comment]
Sorry, this is actually an issue with any Python version if you pre-install cython and force installation from the sdist package -- there's no `_bspl.pyx` file in there. I don't know how we didn't catch this, but it'll be fixed in the next release anyway. Thanks for reporting.
