### ISSUE TITLE
splines for higher order than cubic

### ISSUE THREAD

**Issue by ddevetak** [kb-press/ndsplines#60]
Hello,

ndsplines are by construction of cubic order n = 3. Is it possible as a future venture to have higher orders as for Mathematica interpolation options?

cheers, Damir

**Comment by sixpearls** [comment]
Hi @ddevetak, 

Thanks for your patience. You can construct arbitrary order of polynomials for each axis of the data by changing the `orders` argument in any of the construction methods.  The argument is listed in the [API documentation](https://ndsplines.readthedocs.io/en/latest/api.html) and a brief discussion of order is described in the [mathematics documentation](https://ndsplines.readthedocs.io/en/latest/math.html#order-of-b-spline). I'm going to go ahead and close this, but feel free to comment if you have any other questions and I can re-open it.

Best,
Ben
