### ISSUE TITLE
Prose docs

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#7]
May not be neceessary depending on the detail of the main class's docstring

**Comment by ixjlyons** [comment]
I like the idea of having a page with some info on applications, references, and example use cases. With [sphinx-gallery](https://sphinx-gallery.github.io/), we could just spruce up the example scripts with some notes and call that sufficient for prose docs.

**Comment by sixpearls** [comment]
Yes, I was definitely thinking at least some motivation, application, references, and examples would be necessary in the docs. I was thinking they could go in the docstring of the main class to match the scipy style, but I'm not attached.

**Comment by sixpearls** [comment]
We should also illustrate the difference between boundary conditions and extrapolation. The current `1d-interp.py` demo primarily demonstrates this, so we can just use that. Do we have to demonstrate that the `BSpline` and our spline give the same result over boundary conditions?

Do we need to show, mathematically and/or through example, that it isn't possible to use `ndimage` for anything but linear interpolation if the data isn't uniformly spaced?

**Comment by ixjlyons** [comment]
> We should also illustrate the difference between boundary conditions and extrapolation. The current 1d-interp.py demo primarily demonstrates this, so we can just use that. Do we have to demonstrate that the BSpline and our spline give the same result over boundary conditions?

It could be nice to have an example that focuses on API compatibility and equivalence of results for the 1D case. Maybe the existing 1D example does this well enough?

> Do we need to show, mathematically and/or through example, that it isn't possible to use ndimage for anything but linear interpolation if the data isn't uniformly spaced?

I think this could just be stated (prominently -- it's a pretty important motivation for making ndsplines). If you had something in mind, how would you demonstrate that it can't?

**Comment by sixpearls** [comment]
> Maybe the existing 1D example does this well enough?

As of 8d5e065fd472a492385c4fde8d99815a96e0a0a7, this would be sufficient for me as long as it were easily discover-able in the docs

> If you had something in mind, how would you demonstrate that it can't?

I have my old implementation which didn't work. When it didn't work, I got halfway through a derivation/proof for why it shouldn't then stopped. I guess the best thing would be to complete the derivation/proof, although I'm not sure if it would be appreciated. I guess that's the core of my question.

**Comment by sixpearls** [comment]
To what extent has #17 addressed this?

**Comment by sixpearls** [comment]
#49 will close this
